# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Z3950
version:      0.48
version_from: Z3950.pm
installdirs:  site
requires:
    Event:                         0.77

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
